### ISSUE TITLE
Cannot make a release with the latest change to `release.sh`

### ISSUE THREAD

**Issue by lubosmj** [pulp/plugin_template#833]
It is not possible to perform a release without disabling all the selected options:
![image](https://github.com/pulp/plugin_template/assets/8740962/911f4764-fdc6-425c-a0c7-e1b287430299)

-----------------------------------

The following behaviour is observable in the pulp-container repository after applying the latest changes from the temaplate:
```
remote: error: GH006: Protected branch update failed for refs/heads/2.16.        
remote: error: 5 of 5 required status checks are expected.        
To https://github.com/pulp/pulp_container
 * [new tag]           2.16.4 -> 2.16.4
 ! [remote rejected]   2.16 -> 2.16 (protected branch hook declined)
error: failed to push some refs to 'https://github.com/pulp/pulp_container'
```

The issue is relevant to this line of code: https://github.com/pulp/plugin_template/blob/4288910c65636bc23ce25563917c831fecd9d15a/templates/github/.github/workflows/scripts/release.sh#L26

-----------------------------------

Not to forget that if the script fails to succeed, there is still a new tag created which results into the following error when trying to re-run the job:
```
fatal: tag '2.16.4' already exists
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.8.18/x64/bin/bump2version", line 8, in <module>
    sys.exit(main())
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/bumpversion/cli.py", line 137, in main
    _tag_in_vcs(vcs, context, args)
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/bumpversion/cli.py", line 728, in _tag_in_vcs
    vcs.tag(sign_tags, tag_name, tag_message)
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/bumpversion/vcs.py", line 138, in tag
    subprocess.check_output(command)
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/subprocess.py", line [41](https://github.com/pulp/pulp_container/actions/runs/7629035585/job/20781496890#step:7:42)5, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['git', 'tag', '2.16.4', '--message', 'Release 2.16.4']' returned non-zero exit status 128.
```

**Comment by lubosmj** [comment]
**Consider that the current workflow does not push the package to PyPI.**
